### ISSUE TITLE
stream.js:74       throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by jbeckton** [ajtowf/ng2_play#7]
[20:41:41] Using gulpfile ~/WebstormProjects/4x4RecoveryWebsite/gulpfile.js
[20:41:41] Starting 'ts-lint'...
[20:41:41] Starting 'compile-ts'...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

SyntaxError: Unexpected token r
    at Object.parse (native)
    at RcFinder.loader (/Users/jbeckton/WebstormProjects/4x4RecoveryWebsite/node_modules/rcfinder/index.js:20:17)
    at get (/Users/jbeckton/WebstormProjects/4x4RecoveryWebsite/node_modules/rcfinder/index.js:68:18)
    at respond (/Users/jbeckton/WebstormProjects/4x4RecoveryWebsite/node_modules/rcfinder/index.js:122:22)
    at /Users/jbeckton/WebstormProjects/4x4RecoveryWebsite/node_modules/rcfinder/index.js:173:28
    at /Users/jbeckton/WebstormProjects/4x4RecoveryWebsite/node_modules/rcfinder/index.js:53:7
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by jbeckton** [comment]
Figured out that ts-lint is causing the problem

**Comment by ajtowf** [comment]
Is this even this repo? 4x4RecoveryWebsite? node_modules/rcfinder? We're not linting node_modules directory, closing.
